### ISSUE TITLE
Warning: Accessing non-existent property 'splice' of module exports inside circular dependency

### ISSUE THREAD

**Issue by elena-dumitrescu** [osstotalsoft/nodebb#18]
With higher node version (mine is v14.15.1), I got this warning "Accessing non-existent property 'splice' of module exports inside circular dependency". This warning appears in messageHandler file.

**Comment by oncicaradupopovici** [comment]
NodeBB does not directly use splice in the source code, but it could be a direct or indirect dependency requiring this property.
Use --trace-warnings flag to see the full stack and get more info about what package is actuallly requiring this property.
See https://github.com/nodejs/node/issues/32987
